openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /api/users/:
    get:
      operationId: listget_post_users
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
      - api
    post:
      operationId: createget_post_users
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
  /api/usage/:
    get:
      operationId: listUsages
      description: ''
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      - name: usage_at_start_date
        required: false
        in: query
        description: usage_at_start_date
        schema:
          type: string
      - name: usage_at_end_date
        required: false
        in: query
        description: usage_at_end_date
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 123
                  next:
                    type: string
                    nullable: true
                    format: uri
                    example: http://api.example.org/accounts/?page=4
                  previous:
                    type: string
                    nullable: true
                    format: uri
                    example: http://api.example.org/accounts/?page=2
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/Usage'
          description: ''
      tags:
      - api
    post:
      operationId: createUsage
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Usage'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Usage'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Usage'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usage'
          description: ''
      tags:
      - api
  /api/users/usage/{id}:
    get:
      operationId: retrieveUsage
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique value identifying this usage.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usage'
          description: ''
      tags:
      - api
    put:
      operationId: updateUsage
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique value identifying this usage.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Usage'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Usage'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Usage'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usage'
          description: ''
      tags:
      - api
    patch:
      operationId: partialUpdateUsage
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique value identifying this usage.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Usage'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Usage'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Usage'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usage'
          description: ''
      tags:
      - api
    delete:
      operationId: destroyUsage
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique value identifying this usage.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
  /api-token-auth/:
    post:
      operationId: createAuthToken
      description: ''
      parameters: []
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AuthToken'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/AuthToken'
          application/json:
            schema:
              $ref: '#/components/schemas/AuthToken'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthToken'
          description: ''
      tags:
      - api-token-auth
components:
  schemas:
    Usage:
      type: object
      properties:
        id:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        usage_at:
          type: string
          format: date-time
          readOnly: true
        amount:
          type: number
        user_id:
          type: string
        usage_type_id:
          type: string
      required:
      - id
      - amount
      - user_id
      - usage_type_id
    AuthToken:
      type: object
      properties:
        username:
          type: string
          writeOnly: true
        password:
          type: string
          writeOnly: true
        token:
          type: string
          readOnly: true
      required:
      - username
      - password
